namespace: wackopicko
output:
  file_path: ./reports/results.csv
  format: CSV
strict: true
file_size_limit: 10MB
sast:
  include:
    - .
  exclude:
    - glob(**/node_modules/**)
    - glob(**/test/**)
sca:
  include:
    - .
  exclude:
    - glob(**/test/**)
